//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutPlanner.Tools.Auth {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkoutPlanner.Tools.Auth.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ui_flow.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à App logo.
        /// </summary>
        internal static string fui_accessibility_logo {
            get {
                return ResourceManager.GetString("fui_accessibility_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone number automatically verified.
        /// </summary>
        internal static string fui_auto_verified {
            get {
                return ResourceManager.GetString("fui_auto_verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string fui_button_text_save {
            get {
                return ResourceManager.GetString("fui_button_text_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send.
        /// </summary>
        internal static string fui_button_text_send {
            get {
                return ResourceManager.GetString("fui_button_text_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string fui_cancel {
            get {
                return ResourceManager.GetString("fui_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Follow the instructions sent to {0} to recover your password..
        /// </summary>
        internal static string fui_confirm_recovery_body {
            get {
                return ResourceManager.GetString("fui_confirm_recovery_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue.
        /// </summary>
        internal static string fui_continue {
            get {
                return ResourceManager.GetString("fui_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à @string/app_name.
        /// </summary>
        internal static string fui_default_toolbar_title {
            get {
                return ResourceManager.GetString("fui_default_toolbar_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email account registration unsuccessful.
        /// </summary>
        internal static string fui_email_account_creation_error {
            get {
                return ResourceManager.GetString("fui_email_account_creation_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à email_field.
        /// </summary>
        internal static string fui_email_field_name {
            get {
                return ResourceManager.GetString("fui_email_field_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        internal static string fui_email_hint {
            get {
                return ResourceManager.GetString("fui_email_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm email.
        /// </summary>
        internal static string fui_email_link_confirm_email_header {
            get {
                return ResourceManager.GetString("fui_email_link_confirm_email_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm email to continue sign in.
        /// </summary>
        internal static string fui_email_link_confirm_email_message {
            get {
                return ResourceManager.GetString("fui_email_link_confirm_email_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You originally intended to connect {0} to your email account but have opened the link on a different device where you are not signed in. If you still want to connect your {0} account, open the link on the same device where you started sign-in. Otherwise, tap Continue to sign-in on this device..
        /// </summary>
        internal static string fui_email_link_cross_device_linking_text {
            get {
                return ResourceManager.GetString("fui_email_link_cross_device_linking_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign in with {0}.
        /// </summary>
        internal static string fui_email_link_cross_device_sign_in_button_text {
            get {
                return ResourceManager.GetString("fui_email_link_cross_device_sign_in_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Session ended.
        /// </summary>
        internal static string fui_email_link_different_anonymous_user_header {
            get {
                return ResourceManager.GetString("fui_email_link_different_anonymous_user_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The session associated with this sign-in request has either expired or was cleared..
        /// </summary>
        internal static string fui_email_link_different_anonymous_user_message {
            get {
                return ResourceManager.GetString("fui_email_link_different_anonymous_user_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dismiss.
        /// </summary>
        internal static string fui_email_link_dismiss_button {
            get {
                return ResourceManager.GetString("fui_email_link_dismiss_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A sign-in email with additional instructions was sent to {0}. Check your email to complete sign-in..
        /// </summary>
        internal static string fui_email_link_email_sent {
            get {
                return ResourceManager.GetString("fui_email_link_email_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign-in email sent.
        /// </summary>
        internal static string fui_email_link_header {
            get {
                return ResourceManager.GetString("fui_email_link_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to complete sign in.
        /// </summary>
        internal static string fui_email_link_invalid_link_header {
            get {
                return ResourceManager.GetString("fui_email_link_invalid_link_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The action code is invalid. This can happen if the code is malformed, expired, or has already been used..
        /// </summary>
        internal static string fui_email_link_invalid_link_message {
            get {
                return ResourceManager.GetString("fui_email_link_invalid_link_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resend.
        /// </summary>
        internal static string fui_email_link_resend {
            get {
                return ResourceManager.GetString("fui_email_link_resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trouble getting email?.
        /// </summary>
        internal static string fui_email_link_trouble_getting_email_header {
            get {
                return ResourceManager.GetString("fui_email_link_trouble_getting_email_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If the steps above didn&apos;t work, you can resend the email. Note that this will deactivate the link in the older email..
        /// </summary>
        internal static string fui_email_link_trouble_getting_email_resend_solution {
            get {
                return ResourceManager.GetString("fui_email_link_trouble_getting_email_resend_solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Try these common fixes: \u2022 Check if the email was marked as spam or filtered. \u2022 Check your internet connection. \u2022 Check that you did not misspell your email. \u2022 Check that your inbox space is not running out or other inbox setting related issues..
        /// </summary>
        internal static string fui_email_link_trouble_getting_possible_fixes {
            get {
                return ResourceManager.GetString("fui_email_link_trouble_getting_possible_fixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New device or browser detected..
        /// </summary>
        internal static string fui_email_link_wrong_device_header {
            get {
                return ResourceManager.GetString("fui_email_link_wrong_device_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Try opening the link using the same device or browser where you started the sign-in process..
        /// </summary>
        internal static string fui_email_link_wrong_device_message {
            get {
                return ResourceManager.GetString("fui_email_link_wrong_device_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the 6-digit code we sent to.
        /// </summary>
        internal static string fui_enter_confirmation_code {
            get {
                return ResourceManager.GetString("fui_enter_confirmation_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à That email address doesn&apos;t match an existing account.
        /// </summary>
        internal static string fui_error_email_does_not_exist {
            get {
                return ResourceManager.GetString("fui_error_email_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect password..
        /// </summary>
        internal static string fui_error_invalid_password {
            get {
                return ResourceManager.GetString("fui_error_invalid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There was a problem verifying your phone number.
        /// </summary>
        internal static string fui_error_quota_exceeded {
            get {
                return ResourceManager.GetString("fui_error_quota_exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This code is no longer valid.
        /// </summary>
        internal static string fui_error_session_expired {
            get {
                return ResourceManager.GetString("fui_error_session_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This phone number has been used too many times.
        /// </summary>
        internal static string fui_error_too_many_attempts {
            get {
                return ResourceManager.GetString("fui_error_too_many_attempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unknown error occurred..
        /// </summary>
        internal static string fui_error_unknown {
            get {
                return ResourceManager.GetString("fui_error_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password not strong enough. Use at least {0} character and a mix of letters and numbers.
        /// </summary>
        internal static string fui_error_weak_password_one {
            get {
                return ResourceManager.GetString("fui_error_weak_password_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password not strong enough. Use at least {0} characters and a mix of letters and numbers.
        /// </summary>
        internal static string fui_error_weak_password_other {
            get {
                return ResourceManager.GetString("fui_error_weak_password_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        internal static string fui_idp_name_email {
            get {
                return ResourceManager.GetString("fui_idp_name_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Facebook.
        /// </summary>
        internal static string fui_idp_name_facebook {
            get {
                return ResourceManager.GetString("fui_idp_name_facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GitHub.
        /// </summary>
        internal static string fui_idp_name_github {
            get {
                return ResourceManager.GetString("fui_idp_name_github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Google.
        /// </summary>
        internal static string fui_idp_name_google {
            get {
                return ResourceManager.GetString("fui_idp_name_google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone.
        /// </summary>
        internal static string fui_idp_name_phone {
            get {
                return ResourceManager.GetString("fui_idp_name_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twitter.
        /// </summary>
        internal static string fui_idp_name_twitter {
            get {
                return ResourceManager.GetString("fui_idp_name_twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wrong code. Try again..
        /// </summary>
        internal static string fui_incorrect_code_dialog_body {
            get {
                return ResourceManager.GetString("fui_incorrect_code_dialog_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à That email address isn&apos;t correct.
        /// </summary>
        internal static string fui_invalid_email_address {
            get {
                return ResourceManager.GetString("fui_invalid_email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a valid phone number.
        /// </summary>
        internal static string fui_invalid_phone_number {
            get {
                return ResourceManager.GetString("fui_invalid_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your email address to continue.
        /// </summary>
        internal static string fui_missing_email_address {
            get {
                return ResourceManager.GetString("fui_missing_email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a first and last name..
        /// </summary>
        internal static string fui_missing_first_and_last_name {
            get {
                return ResourceManager.GetString("fui_missing_first_and_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First &amp; last name.
        /// </summary>
        internal static string fui_name_hint {
            get {
                return ResourceManager.GetString("fui_name_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next.
        /// </summary>
        internal static string fui_next_default {
            get {
                return ResourceManager.GetString("fui_next_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Network error, check your internet connection..
        /// </summary>
        internal static string fui_no_internet {
            get {
                return ResourceManager.GetString("fui_no_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string fui_password_hint {
            get {
                return ResourceManager.GetString("fui_password_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Get instructions sent to this email that explain how to reset your password..
        /// </summary>
        internal static string fui_password_recovery_body {
            get {
                return ResourceManager.GetString("fui_password_recovery_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone Number.
        /// </summary>
        internal static string fui_phone_hint {
            get {
                return ResourceManager.GetString("fui_phone_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Privacy Policy.
        /// </summary>
        internal static string fui_privacy_policy {
            get {
                return ResourceManager.GetString("fui_privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checking for existing accounts….
        /// </summary>
        internal static string fui_progress_dialog_checking_accounts {
            get {
                return ResourceManager.GetString("fui_progress_dialog_checking_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading….
        /// </summary>
        internal static string fui_progress_dialog_loading {
            get {
                return ResourceManager.GetString("fui_progress_dialog_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending….
        /// </summary>
        internal static string fui_progress_dialog_sending {
            get {
                return ResourceManager.GetString("fui_progress_dialog_sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signing in….
        /// </summary>
        internal static string fui_progress_dialog_signing_in {
            get {
                return ResourceManager.GetString("fui_progress_dialog_signing_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Signing up….
        /// </summary>
        internal static string fui_progress_dialog_signing_up {
            get {
                return ResourceManager.GetString("fui_progress_dialog_signing_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can&apos;t leave this empty..
        /// </summary>
        internal static string fui_required_field {
            get {
                return ResourceManager.GetString("fui_required_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resend Code.
        /// </summary>
        internal static string fui_resend_code {
            get {
                return ResourceManager.GetString("fui_resend_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resend code in 0:%02d.
        /// </summary>
        internal static string fui_resend_code_in {
            get {
                return ResourceManager.GetString("fui_resend_code_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue as guest.
        /// </summary>
        internal static string fui_sign_in_anonymously {
            get {
                return ResourceManager.GetString("fui_sign_in_anonymously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign in.
        /// </summary>
        internal static string fui_sign_in_default {
            get {
                return ResourceManager.GetString("fui_sign_in_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign in with Apple.
        /// </summary>
        internal static string fui_sign_in_with_apple {
            get {
                return ResourceManager.GetString("fui_sign_in_with_apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign in with email.
        /// </summary>
        internal static string fui_sign_in_with_email {
            get {
                return ResourceManager.GetString("fui_sign_in_with_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign in with Facebook.
        /// </summary>
        internal static string fui_sign_in_with_facebook {
            get {
                return ResourceManager.GetString("fui_sign_in_with_facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign in with GitHub.
        /// </summary>
        internal static string fui_sign_in_with_github {
            get {
                return ResourceManager.GetString("fui_sign_in_with_github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign in with Google.
        /// </summary>
        internal static string fui_sign_in_with_google {
            get {
                return ResourceManager.GetString("fui_sign_in_with_google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign in with Microsoft.
        /// </summary>
        internal static string fui_sign_in_with_microsoft {
            get {
                return ResourceManager.GetString("fui_sign_in_with_microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign in with phone.
        /// </summary>
        internal static string fui_sign_in_with_phone {
            get {
                return ResourceManager.GetString("fui_sign_in_with_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign in with phone number.
        /// </summary>
        internal static string fui_sign_in_with_phone_number {
            get {
                return ResourceManager.GetString("fui_sign_in_with_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign in with Twitter.
        /// </summary>
        internal static string fui_sign_in_with_twitter {
            get {
                return ResourceManager.GetString("fui_sign_in_with_twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign in with Yahoo.
        /// </summary>
        internal static string fui_sign_in_with_yahoo {
            get {
                return ResourceManager.GetString("fui_sign_in_with_yahoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By tapping “{0}”, an SMS may be sent. Message &amp; data rates may apply..
        /// </summary>
        internal static string fui_sms_terms_of_service {
            get {
                return ResourceManager.GetString("fui_sms_terms_of_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By tapping “{0}”, you are indicating that you accept our {1} and {2}. An SMS may be sent. Message &amp; data rates may apply..
        /// </summary>
        internal static string fui_sms_terms_of_service_and_privacy_policy_extended {
            get {
                return ResourceManager.GetString("fui_sms_terms_of_service_and_privacy_policy_extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terms of Service.
        /// </summary>
        internal static string fui_terms_of_service {
            get {
                return ResourceManager.GetString("fui_terms_of_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check your email.
        /// </summary>
        internal static string fui_title_confirm_recover_password {
            get {
                return ResourceManager.GetString("fui_title_confirm_recover_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recover password.
        /// </summary>
        internal static string fui_title_recover_password_activity {
            get {
                return ResourceManager.GetString("fui_title_recover_password_activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sign up.
        /// </summary>
        internal static string fui_title_register_email {
            get {
                return ResourceManager.GetString("fui_title_register_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à @string/fui_sign_in_default.
        /// </summary>
        internal static string fui_title_welcome_back_idp_prompt {
            get {
                return ResourceManager.GetString("fui_title_welcome_back_idp_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à @string/fui_sign_in_default.
        /// </summary>
        internal static string fui_title_welcome_back_password_prompt {
            get {
                return ResourceManager.GetString("fui_title_welcome_back_password_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By continuing, you are indicating that you accept our {0} and {1}..
        /// </summary>
        internal static string fui_tos_and_pp {
            get {
                return ResourceManager.GetString("fui_tos_and_pp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} \u00A0 \u00A0 {1}.
        /// </summary>
        internal static string fui_tos_and_pp_footer {
            get {
                return ResourceManager.GetString("fui_tos_and_pp_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trouble signing in?.
        /// </summary>
        internal static string fui_trouble_signing_in {
            get {
                return ResourceManager.GetString("fui_trouble_signing_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verify Phone Number.
        /// </summary>
        internal static string fui_verify_phone_number {
            get {
                return ResourceManager.GetString("fui_verify_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your phone number.
        /// </summary>
        internal static string fui_verify_phone_number_title {
            get {
                return ResourceManager.GetString("fui_verify_phone_number_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verify your phone number.
        /// </summary>
        internal static string fui_verify_your_phone_title {
            get {
                return ResourceManager.GetString("fui_verify_your_phone_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verifying….
        /// </summary>
        internal static string fui_verifying {
            get {
                return ResourceManager.GetString("fui_verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome back!.
        /// </summary>
        internal static string fui_welcome_back_email_header {
            get {
                return ResourceManager.GetString("fui_welcome_back_email_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You already have an account.
        /// </summary>
        internal static string fui_welcome_back_email_link_header {
            get {
                return ResourceManager.GetString("fui_welcome_back_email_link_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You&apos;ve already used {0}. You can connect your {1} account with {0} by signing in with email link below. For this flow to successfully connect your {1} account with this email, you have to open the link on the same device or browser..
        /// </summary>
        internal static string fui_welcome_back_email_link_prompt_body {
            get {
                return ResourceManager.GetString("fui_welcome_back_email_link_prompt_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You already have an account.
        /// </summary>
        internal static string fui_welcome_back_idp_header {
            get {
                return ResourceManager.GetString("fui_welcome_back_idp_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You&apos;ve already used {0}. Sign in with {1} to continue..
        /// </summary>
        internal static string fui_welcome_back_idp_prompt {
            get {
                return ResourceManager.GetString("fui_welcome_back_idp_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You&apos;ve already used {0} to sign in. Enter your password for that account..
        /// </summary>
        internal static string fui_welcome_back_password_prompt_body {
            get {
                return ResourceManager.GetString("fui_welcome_back_password_prompt_body", resourceCulture);
            }
        }
    }
}
